<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Richard Lander</Authors>
    <Description>Extract and verify SourceLink metadata from .NET assemblies</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>
